### ISSUE TITLE
please offer more examples?

### ISSUE THREAD

**Issue by sixyang** [zassou65535/image_converter#1]
Does it work for real life photos?

**Comment by zassou65535** [comment]
According to <a href="https://arxiv.org/abs/1907.10830">the original paper</a>, It can convert real life photos.
Around the bottom of the paper, some style transfer tasks are introduced, such as photo→portrait, selfie→anime, cat→dog, and so on.
Given these results, depends on the hyperparameter, It can work.
Thank you for your interest in my repository!!!!

**Comment by sixyang** [comment]
> 

Thanks for your work!
